export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/mall/index',
    'pages/message/index',
    'pages/profile/index',
    'pages/login/index',
    'pages/teacher/list',
    'pages/teacher/detail',
    'pages/org/list',
    'pages/org/detail',
    'pages/orders/index',
    'pages/order-detail/index',
    'pages/publish-demand/index',
    'pages/publish-moment/index',
    'pages/member/index',
    'pages/activities/index',
    'pages/activity-detail/index',
    'pages/my-activities/index',
    'pages/pay/index',
    'pages/pay-result/index',
    'pages/teacher-auth/index',
    'pages/org-auth/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '棉花糖教育',
    navigationBarTextStyle: 'black'
  },
  tabBar: {
    color: '#6B7280',
    selectedColor: '#2563EB',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: './assets/tabbar/home.png',
        selectedIconPath: './assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/mall/index',
        text: '商城',
        iconPath: './assets/tabbar/mall.png',
        selectedIconPath: './assets/tabbar/mall-active.png',
      },
      {
        pagePath: 'pages/message/index',
        text: '消息',
        iconPath: './assets/tabbar/message.png',
        selectedIconPath: './assets/tabbar/message-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: './assets/tabbar/user.png',
        selectedIconPath: './assets/tabbar/user-active.png',
      },
    ],
  },
})
